version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - echo "Building SPA"
      - SPA=1 npm run build:env   # ou: npm run build:spa
artifacts:
  files:
    - '**/*'
  base-directory: build/client